# Generated by Django 5.0.4 on 2024-05-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='image',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='songName',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
    ]
