# Generated by Django 5.0.4 on 2024-05-04 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_rename_song_id_song_id_rename_image_song_poster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='poster',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='id',
            new_name='song_id',
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
